name: Publish teenstudy to PyPI 

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build-n-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@master

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PUBLISH_TEENSTUDY }}
